# i) Concatenation and sorting of array

In [1]:
import numpy as np
x = np.array([1,2,3,4])
y = np.array([5,6,7,8])

In [2]:
np.concatenate([x,y])    # Concatenating the 2 NumPy arrays, x and y

array([1, 2, 3, 4, 5, 6, 7, 8])

# ii) Matrix multiplication is called dot product in NumPy

In [3]:
''' For matrix multiplication or dot product, the number of column in the first matrix should be equal to the no of 
rpw in the second matrix'''
a = np.array([[1,2,3], [4,5,6]])
b = np.array([[7,8],[9,10],[11,12]])
print(np.dot(a,b))

[[ 58  64]
 [139 154]]


# iii) Matrix Operation (Performed by "Linear Algebra" module)

### **Note:- A matrix having a single row is called a row matrix and that having a single column is called a column matrix**
<img src = "https://i.ytimg.com/vi/8hOFwKw9r8w/sddefault.jpg">

## **a) Determinant**

In [4]:
matrix = np.array([[1,7],[3,1]])
np.linalg.det(matrix)

-20.000000000000007

## **b) Inverse**

In [5]:
np.linalg.inv(matrix)

array([[-0.05,  0.35],
       [ 0.15, -0.05]])

## **c) Transpose**

In [6]:
matrix.T

array([[1, 3],
       [7, 1]])

## **d) Row and Column matrix**

In [7]:
x = np.array([[1],[2]])
x.reshape([-1,1])    #(Put -1 if row no or the column no is unknown)

array([[1],
       [2]])

## **e) Matrix Sum**

## **The axis arguement in NumPy: 2D axis= 0 is column-wise and axis= 1means row-wise**

In [8]:
x1 = np.array([[1,2,3],[4,5,6]])
print(x1.sum())  # The sum of all items of matrix
print(x1.sum(axis=0)) # Column-wise sum 
print(x1.sum(axis=1)) # Row-wise sum

21
[5 7 9]
[ 6 15]


# iv) Statistics using NumPy

In [9]:
np.random.seed(2023)
numbers = np.random.randint(1,100,20)
print(numbers)

[88 26 71 56 34 93  4 53 87 97 23 18 54 48 78 40 70 89  4 59]


## **a) Mean**

In [10]:
np.mean(numbers) # First_method
numbers.mean()   # Second_method

54.6

## **b) Max and Min numbers in an array**

In [11]:
large = np.max(numbers)
small = np.min(numbers)
print(large)
print(small)

97
4


## **c) To find out the index of largest and smallest value in an array**

In [12]:
print(np.argmax(numbers))
print(np.argmin(numbers))

9
6


## **d) Standard Deviation**

In [13]:
np.std(numbers)

28.858967410494785

## **e) Variance (Square of the standard deviation is called the variance)**

In [14]:
np.var(numbers)

832.8400000000001

## **f) Mode**

In [ ]:
from scipy.stats import mode
mode(numbers)

In [1]:
import numpy as np
import seaborn as sns
df = sns.load_dataset('tips')

In [2]:
df.head()

total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4